# FOR DEV PURPOSES ONLY

# For more information, please refer to https://aka.ms/vscode-docker-python
FROM ubuntu:22.04

# Apt and installing things
# RUN echo 'APT::Install-Suggests "0";' >> /etc/apt/apt.conf.d/00-docker
# RUN echo 'APT::Install-Recommends "0";' >> /etc/apt/apt.conf.d/00-docker

ENV DEBIAN_FRONTEND=noninteractive 

RUN apt update
RUN apt -y install software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt update
RUN apt -y install python3.12-full
# RUN rm -rf /var/lib/apt/lists/*

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

WORKDIR /skyblue
COPY . /skyblue

# Install pip requirements
RUN python3.12 -m ensurepip --upgrade
RUN python3.12 -m pip install -r requirements.txt

# During debugging, this entry point will be overridden. For more information, please refer to https://aka.ms/vscode-docker-python-debug
# CMD ["python", "src\main.py"]
# CMD python src/main.py
ENTRYPOINT [ "bash" ]
